### ISSUE TITLE
Creating Dungeons in a loop creates the same dungeon?

### ISSUE THREAD

**Issue by hamogor** [Meshiest/go-dungeon#2]
```
func DunTest() {
	x := 15
	for i := 0; i < 10; i++ {
		d := NewDungeon(64, x + 10)
		d.Print()
	}
}
```

I'm trying to create a number of dungeons and store them in a slice to make going up and down stairs easier for myself. However this function returns 10 identical dungeons, even when adding 10 to the number of room attempts. Why is this?

**Comment by Meshiest** [comment]
https://github.com/Meshiest/go-dungeon/blob/master/dungeon/dungeon.go#L87

Dungeon Generation seeds are based on Unix time. You're likely creating them within the same second.

You can generate dungeons without `NewDungeon` if you're interested in changing the seed!

**Comment by hamogor** [comment]
Gotcha! Thanks for clearing that up for me.
